### PR TITLE
Add Docker support (hold for review)

### PR DESCRIPTION
**Pull request by jcam**
This PR adds support to run the application from docker containers

### CODE REVIEW

**Comment by kelsh** [comment]
hey sorry no one got back to you sooner on this.  Awesome job! testing soon.

**Comment by kelsh** [comment]
Hi @jcam.  So all in all thank you for doing this. 
- Not ideal to lock php to 7.1.3.  If php versions are going to be incompatible with laraval I guess we have to though
- I didn't have a dev scripts folder with this branch so i had to move the testrig script.
- change "source" to "." for better compatibility with different environments
- There were a couple folder permission issues with the container, particularly /storage/logs and /framework/views
- got a laravel error saying no supported encryption cypher, but stopping and starting the container made that error go away???  Didn't figure out the cause of that one, worst case is docker is copying something from the host system for encryption?
- testrig script should make .env.testing if it doesn't exist

I'm not sure of all the conventions for this repo and also I'm not familiar with working across forks on github.  If it was up to me I would copy this branch to the repo, fix the couple things i mentioned and accept it.  Not sure what the etiquette is for making commits on other people's forks.   

More or less accepted though, and we thank you for the effort.

**Comment by demogorgonzola** [comment]
So there are a few outstanding things which make both the test and production environment a little unwieldy. Most of which @kelsh have already addressed.

- When it comes to setting up the database it seems like you've already got everything down. I would add a ```docker-compose down --volumes``` in the ```testrig.sh``` to allow any configurations you make in the ```docker-compose.yml```'s to be reflected rather than be persisted in volumes for testing.

- There's a permissioning error with your log and cache files, I've narrowed it down to two problems. The first being that you choose a ```target``` in your ```docker-compose.override.yml``` which only stages ```phpfpm```. I noticed there's a little indirection when using the ```composer.sh``` and ```npm.sh``` scripts to do something similar the other two stages do, but you're stopping yourself from reaching the ```chown```. If you can either declare ownership to be traded in your ```testrig.sh``` to clear cache and then give it to back ```www-data```, or do so in the docker file. If you do it in the docker file, remember the intermediate container is being thrown out, so declaring a ```VOLUME``` mount after you make the ```chown``` would help persist that change.

- the "dev-scripts" in the read me should be changed to "scripts", just a typo thing

otherwise, this is great!

**Comment by demogorgonzola** [comment]
it also seems like you're using ```phpfpm``` as two separate stages in the ```app.dockerfile```, it only executes the first and leaves the other enitrely alone which may be the bug you're looking for

**Comment by jcam** [comment]
Sorry I got sucked into work and event craziness and didn't follow these comments. @kelsh if you want to make some commits against my fork, go for it!
I don't think I'll have time to tweak this more until after the big burn :/

**Comment by itsrachelfish** [comment]
Obsoleted by #199

**Pull request closed without merging**
